### ISSUE TITLE
hello,Quote Multi -line text and label notes cannot be exported correctly after searching

### ISSUE THREAD

**Issue by doriszhang2020** [metawops/obsidian-table-to-csv-export#2]
![image](https://user-images.githubusercontent.com/104901283/173168894-f9caacfb-6ff7-45b8-b2f4-2d118f779116.png)

**Comment by metawops** [comment]
Hi Doris,
I‘m having difficulties to recognize what the problem is. I‘d really need the HTML of the preview (reading) mode. Currently, I don‘t see a table at all in the preview pane. And I don‘t see a `dataview` block with a query, either.
Can you please create a really simple note with one `dataview` code block that shows the problem you have and attach that markdown here? So that I can recreate the problem on my side. Thank you!

**Comment by doriszhang2020** [comment]
this is csv---[Dataview 卡片笔记-006.csv](https://github.com/metawops/obsidian-table-to-csv-export/files/8883535/Dataview.-006.csv)
this is one of my notes.
![image](https://user-images.githubusercontent.com/104901283/173180868-a2746098-7d07-4002-af40-c992d0f82816.png)

this is dataviewjs. the dataview block of the function is to choose a notes with color with color selection
![image](https://user-images.githubusercontent.com/104901283/173180926-e52ad337-22c7-498a-91ec-883b42712aae.png)

**Comment by doriszhang2020** [comment]
[Dataview 卡片笔记.pdf](https://github.com/metawops/obsidian-table-to-csv-export/files/8883566/Dataview.pdf)

**Comment by metawops** [comment]
Wow, this ist really complex. To be able to debug the problem I'd really need the HTML code of the rendered markdown. 
I haven't experimented with `dataviewjs` yet, but in the end, it produces an HTML `<table>` just like any normal `dataview` DQL query. 
I would be really helpful if you could narrow down the problem in a blank, new vault with a single new note and share that vault so that I can have a look at the HTML of the preview pane. 
I'm not able to debug anything here just based on your screenshots or PDF files.
From the CSV file, on the other hand, I suspect there might be a problem with the quoting of the data cells. My plugin currently only quotes individual data cells with the (hard-coded) `"` character and there seems to be a mismatch of those characters.
Can you pst a screenshot of my plugin's settings? I assume the "Quote data" switch is on? Have you tried to switch it off and see what happens then?
Meanwhile I'll try to make a new version of my plugin that allows for selecting different quotation characters.

**Comment by metawops** [comment]
Oh! And another problem might be that you have hard returns inside of cells. This won't work in a CSV file, of course. 
I could add a setting that allows for replacing hard returns with a space character or similar ... I'll think of it.

**Comment by doriszhang2020** [comment]
Thank you very much，but I am a non -professionals, I don’t understand the professional terms you said. Can you  modify the plug -in and use a picture  how to configure it to help me solve this problem.

> Oh! And another problem might be that you have hard returns inside of cells. This won't work in a CSV file, of course. I could add a setting that allows for replacing hard returns with a space character or similar ... I'll think of it.

**Comment by metawops** [comment]
No worries, Doris, I'm quite certain that the problem you see is because you have return characters in your data.
I made a new release of my plugin, version [0.1.3](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.3).
Please try this. It has a new setting that allows for the handling of those return characters in data cells.
Here's a screenshot of that setting. You can try any of the three settings. Each handles the replacement of return characters differently:
![Screenshot 2022-06-11 at 14 35 22](https://user-images.githubusercontent.com/376090/173188169-b915c7f3-77a4-4388-9d86-420692d9d791.png)
The middle one is pre-selected and might be the best choice for your case.
Please report back if that helps or even solves your issue.

**Comment by doriszhang2020** [comment]
> No worries, Doris, I'm quite certain that the problem you see is because you have return characters in your data. I made a new release of my plugin, version [0.1.3](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.3). Please try this. It has a new setting that allows for the handling of those return characters in data cells. Here's a screenshot of that setting. You can try any of the three settings. Each handles the replacement of return characters differently: ![Screenshot 2022-06-11 at 14 35 22](https://user-images.githubusercontent.com/376090/173188169-b915c7f3-77a4-4388-9d86-420692d9d791.png) The middle one is pre-selected and might be the best choice for your case. Please report back if that helps or even solves your issue.

thanks,but I meet a new problem,The exported CSV file, Instead of text that cannot be recognized in Chinese, and the content and title of the first line are mixed in the same line
[-008.csv](https://github.com/metawops/obsidian-table-to-csv-export/files/8884044/-008.csv)
。
However,the content of Copy to clipboard(Ctrl+V),is right
[obsidian-note-ctrl+V.pdf](https://github.com/metawops/obsidian-table-to-csv-export/files/8884051/obsidian-note-ctrl%2BV.pdf)
.
and this dataview list.
[Dataview 卡片笔记.pdf](https://github.com/metawops/obsidian-table-to-csv-export/files/8884054/Dataview.pdf)

**Comment by metawops** [comment]
Okay, the next problem seems to be that you have the " character inside your table cells (around the `zotero://...` link) _AND_ have the "Quote data" switch in my plugin's setting ON. What happens if you switch that OFF and export?

I'll prepare another new version where one can chose the quotation character. In your case, the `"` character makes no sense because it's already inside your cell data. 😉

**Comment by doriszhang2020** [comment]
> Okay, the next problem seems to be that you have the " character inside your table cells (around the `zotero://...` link) _AND_ have the "Quote data" switch in my plugin's setting ON. What happens if you switch that OFF and export?
> 
> I'll prepare another new version where one can chose the quotation character. In your case, the `"` character makes no sense because it's already inside your cell data. 😉
"Quote data" switch off,this is the new csv,still the problem is here,and I cant find any the Correct Chinese characters in the csv
[-007.csv](https://github.com/metawops/obsidian-table-to-csv-export/files/8884123/-007.csv)

**Comment by metawops** [comment]
Okay, next problem: you have a lot of comma characters inside your data cells. So you should change the "Data fields separation character" to something different than the comma. You have to change it to a character that's NOT appearing inside your data cells. Maybe try a semicolon instead? I couldn't find a semicolon inside your data. This might work!
![Screenshot 2022-06-11 at 16 35 04](https://user-images.githubusercontent.com/376090/173192285-6a030f06-5324-4dac-81b8-117ba24115cf.png)

**Comment by metawops** [comment]
There's a new release, [0.1.4](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.4) you can try. It allows to select different data quotation characters (`"` or `'`) from a dropdown and has another new dropdown to select the field separator character (in your case, the semicolon might work best but there are other options; but to be on the safe side so that MS Excel can import the CSV data without problems, you should stick to the semicolon).

**Comment by doriszhang2020** [comment]
> There's a new release, [0.1.4](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.4) you can try. It allows to select different data quotation characters (`"` or `'`) from a dropdown and has another new dropdown to select the field separator character (in your case, the semicolon might work best but there are other options; but to be on the safe side so that MS Excel can import the CSV data without problems, you should stick to the semicolon).

this is the setting
![image](https://user-images.githubusercontent.com/104901283/173207831-cb995ace-80f0-4b33-9e32-b670e7e72d03.png)
this is the csv.And the chinese is wrong.
![image](https://user-images.githubusercontent.com/104901283/173207848-739fa68b-5d3b-452a-873c-f2ece96bf824.png)

[-000.csv](https://github.com/metawops/obsidian-table-to-csv-export/files/8884865/-000.csv)

**Comment by metawops** [comment]
I don't understand what you mean with "the Chinese is wrong"?!
The structure of the CSV file now seems to be correct, I can import it without any errors regarding rows or columns:

<img width="1015" alt="Screenshot 2022-06-12 at 09 09 44" src="https://user-images.githubusercontent.com/376090/173221802-37b0b0ad-7d2b-43e5-b7d5-0c69d1274b6b.png">

I can't read Chinese so I don't see any problems here now. 🤷‍♂️

**Comment by doriszhang2020** [comment]
> I don't understand what you mean with "the Chinese is wrong"?! The structure of the CSV file now seems to be correct, I can import it without any errors regarding rows or columns:
> 
> <img alt="Screenshot 2022-06-12 at 09 09 44" width="1015" src="https://user-images.githubusercontent.com/376090/173221802-37b0b0ad-7d2b-43e5-b7d5-0c69d1274b6b.png">
> 
> I can't read Chinese so I don't see any problems here now. 🤷‍♂️

oh,I use Excel software to open this CSV file，U can see the wrong Chinese  in the csv.Maybe its about Code system problem（UFT-8??）
![image](https://user-images.githubusercontent.com/104901283/173222695-3beb084f-5a6f-47a3-a68a-28f5c10cef37.png)

**Comment by metawops** [comment]
Maybe there‘s something off in your Excel CSV import settings? 😳 
I imported your CSV into Apple Numbers and it seemed to work fine without any change in settings for the import process. 🤷‍♂️ 
I almost never use Excel privately but I can check with your CSV file and Excel tomorrow at my work PC.

**Comment by doriszhang2020** [comment]
> I don't understand what you mean with "the Chinese is wrong"?! The structure of the CSV file now seems to be correct, I can import it without any errors regarding rows or columns:
> 
> <img alt="Screenshot 2022-06-12 at 09 09 44" width="1015" src="https://user-images.githubusercontent.com/376090/173221802-37b0b0ad-7d2b-43e5-b7d5-0c69d1274b6b.png">
> 
> I can't read Chinese so I don't see any problems here now. 🤷‍♂️

thanks very much,I have solved the problem.

**Comment by metawops** [comment]
Awesome! 👍👍
